version: '3'

services:
  web-primary:
    build: .
    image: peld:latest
    restart: always
    command: python3 main.py
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    environment: &web-env
      - SERVER_NAME=${SERVER_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ESI_SECRET_KEY=${ESI_SECRET_KEY}
      - ESI_CLIENT_ID=${ESI_CLIENT_ID}

  web-worker1:
    image: peld:latest
    restart: always
    command: python3 main.py
    expose:
      - "5000"
    depends_on:
      - web-primary
    environment: *web-env

  web-worker2:
    image: peld:latest
    restart: always
    command: python3 main.py
    expose:
      - "5000"
    depends_on:
      - web-primary
    environment: *web-env

  web-worker3:
    image: peld:latest
    restart: always
    command: python3 main.py
    expose:
      - "5000"
    depends_on:
      - web-primary
    environment: *web-env

  web-worker4:
    image: peld:latest
    restart: always
    command: python3 main.py
    expose:
      - "5000"
    depends_on:
      - web-primary
    environment: *web-env
  
  # add extra workers here

  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db

  redis:
    image: redis:latest
    restart: always
    expose:
      - "6379"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/:/usr/share/nginx/html/static/:ro
      - ./nginx.conf.template:/etc/nginx/templates/peld.conf.template:ro
      - /etc/letsencrypt/live/${SERVER_NAME}/fullchain.pem:/etc/nginx/certs/certificate.pem
      - /etc/letsencrypt/live/${SERVER_NAME}/privkey.pem:/etc/nginx/certs/key.pem
    depends_on:
      - web-worker1
    environment:
      - SERVER_NAME=${SERVER_NAME}
